FROM python:3.8.0-buster
RUN pip -q install pip --upgrade
WORKDIR /Users/zakijefferson/code/Threat-Detection
COPY . .

RUN apt-get update ##[edited]
RUN apt-get install 'ffmpeg'\
    'libsm6'\ 
    'libxext6'  -y

RUN pip install -r requirements.txt

COPY . .

RUN apt-get update
RUN apt-get install -qqy x11-apps

RUN pip install jupyter

CMD ["jupyter", "notebook", "--port=8888", "--no-browser", "--ip=0.0.0.0", "--allow-root"]

# Copy all the above into container
COPY . .